---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-vmalertrules
data:
  rule_file_vm.yaml: |+
    name: VMAgentLocalDiskLimitReached
    type: any
    index: logstash-*
    query_key: site_name
    filter:
    - query:
        query_string:
          query: 'log: "D400 - Doesn't Removed old metrics" AND application_name: s3uploader'
    alert: my_alerts.AlertManager
    labels:
      log_ingestion_string: 'D400 - Removed old metrics'
      severity: major
      kafka: 'false'
      smart_alert: 'false'
      host_impacted:
      component: 'telemetry'
      remediation: 'true'
      alertsrc: ElasticSearch
      wikilink:
    annotations:
      description: VMAgent - Error while sending files to S3 and Local Ephemeral storage reached Limit.
      summary: VMAgent - Error while sending files to S3 and Local Ephemeral storage reached Limit.
    nextrulename: VMAgentSNSPublishError
    type: any
    index: logstash-*
    query_key: vcmts_ppod
    filter:
    - query:
        query_string:
          query: 'log: "Unable to Publish" AND (application_name: s3uploader)'
    alert: my_alerts.AlertManager
    labels:
      log_ingestion_string: 'Unable to Publish'
      severity: major
      kafka: 'false'
      smart_alert: 'false'
      host_impacted:
      component: 'telemetry'
      remediation: 'true'
      alertsrc: ElasticSearch
      wikilink:
    annotations:
      description: VMAgent - Error Unable to Publish SNS after retries.
      summary: VMAgent - Error Unable to Publish SNS after retries.
    nextrulename: VMAgentScrapeTimeoutError
    type: frequency
    index: logstash-*
    num_events: 30
    timeframe:
      minutes: 5
    query_key: vcmts_ppod
    filter:
    - query:
        query_string:
          query: '(log:"from job vcmts_metrics_usperf" OR log:"from job vcmts_metrics_other" OR log:"from job vcmts_metrics_m") AND (log:"*error when  scraping") AND (log:"*TCP address timed out")  AND (application_name:"vmagent")'
    alert: my_alerts.AlertManager
    labels:
      log_ingestion_string: 'error when scraping,TCP address timed out'
      severity: major
      kafka: 'false'
      smart_alert: 'false'
      host_impacted:
      component: 'telemetry'
      remediation: 'true'
      alertsrc: ElasticSearch
      wikilink:
    annotations:
      description: VMAgent - VCMTS Metrics scrape is getting timeout.
      summary: VMAgent - VCMTS Metrics scrape is getting timeout.
    nextrulename: MatchmakerKubeApiError
    type: any
    index: logstash-*
    realert:
      minutes: 10
    query_key: namespace
    filter:
    - query:
        query_string:
          query: '(log:"Configured service account doesn't have access. Service account may have been revoked. Unauthorized") AND (application_name: matchmaker) AND (site_name: caamcc100)'
    alert: my_alerts.AlertManager
    labels:
      severity: info
      alertsrc: ElasticSearch
      host_impacted: vcmts-bo
    annotations:
      description:  Error has occurred when Matchmaker is trying to communicate with Kube API server.
      summary: This alert will trigger if there is error in communicating with Kube API server.
    
