---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  rule_file_vm.yaml: |+
    name: DiskLimitReached
    type: any
    index: logstash-*
    query_key: name
    filter:
    - query:
        query_string:
          query: 'log: "D400 - Doesn''t Removed old metrics" AND application_name: s3uploader'
    alert: my_alerts
    labels:
      log_ingestion_string: 'D400 - Removed old metrics'
      severity: major
      kafka: 'false'
      smart_alert: 'false'
      wikilink:
    annotations:
      description: Error while sending files to S3 and Local Ephemeral storage reached Limit.
      summary: Error while sending files to S3 and Local Ephemeral storage reached Limit.
    nextrulename: SNSPublishError
    type: any
    index: logstash-*
    query_key: name
    filter:
    - query:
        query_string:
          query: 'log: "Unable to Publish" AND (application_name: s3uploader)'
    alert: my_alerts
    labels:
      log_ingestion_string: 'Unable to Publish'
      severity: major
      kafka: 'false'
      smart_alert: 'false'
      wikilink:
    annotations:
      description: Error Unable to Publish SNS after retries.
      summary: Error Unable to Publish SNS after retries.
    nextrulename: ScrapeTimeoutError
    type: frequency
    index: logstash-*
    num_events: 30
    timeframe:
      minutes: 5
    query_key: name
    filter:
    - query:
        query_string:
          query: '(log:"from job vcmts_metrics_usperf" OR log:"from job vcmts_metrics_other" OR log:"from job vcmts_metrics_m") AND (log:"*error when  scraping") AND (log:"*TCP address timed out")  AND (application_name:"vmagent")'
    alert: my_alerts
    labels:
      log_ingestion_string: 'error when scraping,TCP address timed out'
      severity: major
      kafka: 'false'
      smart_alert: 'false'
      wikilink:
    annotations:
      description: Metrics scrape is getting timeout.
      summary: Metrics scrape is getting timeout.
    nextrulename: ApiError
    type: any
    index: logstash-*
    realert:
      minutes: 10
    query_key: name
    filter:
    - query:
        query_string:
          query: '(log:"Configured service account doesn''t have access. Service account may have been revoked. Unauthorized") AND (application_name: matchmaker) AND (site_name: caamcc100)'
    alert: my_alerts
    labels:
      severity: info
      alertsrc: ElasticSearch
      host_impacted: vcmts-bo
    annotations:
      description:  Error has occurred when Matchmaker is trying to communicate with Kube API server.
      summary: This alert will trigger if there is error in communicating with Kube API server.
