---
name: Validate-YAML

on:
  push:
    branches: [main, dev, preprod]
  pull_request:
    branches: [main, dev, preprod]

jobs:
  validate-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate YAML file
        run: |
          yamllint -d "{extends: default, rules: {line-length: disable}}" configmap-vmalertrules.yaml
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - run: python yaml_validator.py
