# name: Validate-YAML

# on:
#   push:
#     branches: [main, dev, preprod]
#   pull_request:
#     branches: [main, dev, preprod]

# jobs:
#   validate-yaml:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Validate YAML file
#         run: |
#           yamllint -d "{extends: default, rules: {line-length: disable}}" configmap-vmalertrules.yaml
#       - uses: actions/setup-python@v5
#         with:
#           python-version: '3.10'
#       - name: Run Python script to validate YAML
#         run: python .github/workflows/yaml_validator.py

name: test-action

on:
  push:
    branches: [main, dev, preprod]
  pull_request:
    branches: [main, dev, preprod]

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - TEST_NAME: "Latest v2"
            AWS_CLI_VERSION: "2"
          - TEST_NAME: "Specific v2"
            AWS_CLI_VERSION: "2.0.30"
          - TEST_NAME: "Latest v1"
            AWS_CLI_VERSION: "1"
          - TEST_NAME: "Specific v1"
            AWS_CLI_VERSION: "1.32.15"
          - TEST_NAME: "No Input"
    name: Test ${{ matrix.TEST_NAME }} ${{ matrix.AWS_CLI_VERSION }}
    steps:
      - name: Test ${{ matrix.TEST_NAME }}
        id: install-aws-cli
        uses: unfor19/install-aws-cli-action@master
        with:
          version: ${{ matrix.AWS_CLI_VERSION }}
      - run: aws --version
        shell: bash
      - run: aws s3 ls
        shell: bash
