# name: Validate-YAML

# on:
#   push:
#     branches: [main, dev, preprod]
#   pull_request:
#     branches: [main, dev, preprod]

# jobs:
#   validate-yaml:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Validate YAML file
#         run: |
#           yamllint -d "{extends: default, rules: {line-length: disable}}" configmap-vmalertrules.yaml
#       - uses: actions/setup-python@v5
#         with:
#           python-version: '3.10'
#       - name: Run Python script to validate YAML
#         run: python .github/workflows/yaml_validator.py

name: test-action

on:
  push:
    branches: [main, dev, preprod]
  pull_request:
    branches: [main, dev, preprod]

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - TEST_NAME: "Latest v2"
            AWS_CLI_VERSION: "2"
          - TEST_NAME: "No Input"
    name: Test ${{ matrix.TEST_NAME }} ${{ matrix.AWS_CLI_VERSION }}
    steps:
      - name: Test ${{ matrix.TEST_NAME }}
        id: install-aws-cli
        uses: unfor19/install-aws-cli-action@master
        with:
          version: ${{ matrix.AWS_CLI_VERSION }}
      - run: aws --version
        shell: bash

      - run: aws s3api select-object-content \
          --expression "SELECT * FROM s3object s where (s."log" LIKE '%D400 - Removed old metrics%' AND  s."application_name" LIKE '%s3uploader%') OR (s."log" LIKE '%Unable to Publish%' AND  s."application_name" LIKE '%s3uploader%') OR ((s."log" LIKE '%from job vcmts_metrics_usperf%'  OR s."log" LIKE '%from job vcmts_metrics_other%'  OR s."log" LIKE '%from job vcmts_metrics_m%') AND  (s."log" LIKE '%error when  scraping%') AND  (s."log" LIKE '%TCP address timed out%') AND  (s."application_name" LIKE '%vmagent%')) OR ((s."log" LIKE '%LCCE IP is not available for rphy %'  OR s."log" LIKE '%LCCE IP is not available for rphy%'  OR s."log" LIKE '%NSI Prov IPv6 is not available for rphy%') AND  (s."log" LIKE '%Not proceeding further%') AND  (s."application_name" LIKE '%matchmaker%')) OR ((s."log" LIKE '%Rphy CRD validation failed for rphy%') AND  (s."application_name" LIKE '%matchmaker%')) OR (s."log" LIKE '%errorText%' AND  s."log" LIKE '%validationFailed%' AND  s."container_name" LIKE '%matchmaker_%' AND  s."NOT log" LIKE '%validated%') OR (s."log" LIKE '%The MdName%' AND  s."log" LIKE '%already associated with a different rphyMac%' AND  s."container_name" LIKE '%matchmaker%') OR ((s."log" LIKE '%Configured service account doesn''t have access. Service account may have been revoked. Unauthorized%') AND  (s."application_name" LIKE '%matchmaker%') AND  (s."site_name" LIKE '%caamcc100%'  OR s."site_name" LIKE '%ilhmcc100%')) OR (s."log" LIKE '%evtId=66070413%' AND  s."container_name" LIKE '%vcmts%') OR (s."message" LIKE '%GPS loss of signal%' AND  s."application_name" LIKE '%timeserver%') OR (s."message" LIKE '%Time reference disqualified as system%' AND  s."application_name" LIKE '%timeserver%') OR (s."log" LIKE '%nmulti-chassis-protection link is not configured%' AND  s."application_name" LIKE '%fib_r_bsod_configurator%') OR (s."log" LIKE '%invalid command%' AND  s."application_name" LIKE '%fib_r_bsod_configurator%') OR (s."log" LIKE '%Config diff successfully committed on the switch%' AND  s."application_name" LIKE '%video_src_redun%') OR (s."log" LIKE '%Sample Alert Testing via %' AND  s."container_name" LIKE '%elastalert%') OR (s."application_name" LIKE '%network_monitor%' AND  s."log" LIKE '%Git Pull or Clone Failed for atleast one repos%') OR (s."application_name" LIKE '%network_monitor%' AND  s."log" LIKE '%Unable to start daemon%') OR (s."application_name" LIKE '%network_monitor%' AND  s."log" LIKE '%Mandatory scripts directory%' AND  s."log" LIKE '%missing on Device:%') OR (s."application_name" LIKE '%tusc%' AND  s."log" LIKE '%Invalid gcp_%') OR (s."Message" LIKE '%Received error message from RPD%' AND  s."log" LIKE '%Invalid length 0 for TLV 96.5; Length must be 4%') OR (s."log" LIKE '%core dumped%' AND  s."application_name" LIKE '%gcp%') OR ( s."message" LIKE '%CT=GPS Antenna Alarm Indication,LOC=Near,NC=MN%') OR ( s."message" LIKE '%CT=Time Clock Not Locked,LOC=Near,NC=MN%') OR ( s."message" LIKE '%CT=Communication Failure,LOC=Near,NC=MN%') OR (s."message" LIKE '%ALM:ACCESS PORT%' AND  s."message" LIKE '%CT=Link Down,LOC=Near,NC=CR%') OR ( s."message" LIKE '%CT=No Satellites Tracked,LOC=Near,NC=CR%') OR ( s."message" LIKE '%CT=PWR: No Input Or Unit Fault,LOC=Near,NC=MJ%') OR ( s."message" LIKE '%CT=Time Reference Forced Switch,LOC=Near,NC=MN%') OR (s."log" LIKE '%Event: MAC_DOMAIN_ALREADY_EXISTS%' AND  s."log" LIKE '%Message: MAC domain has already been created%' AND  s."log" LIKE '%Role: standby%') OR ( s."log" LIKE '%watchdog: BUG: soft lockup%') OR (s."log" LIKE '%Assertion%' AND  s."application_name" LIKE '%uspp%')" \
          --expression-type 'SQL' \
          --input-serialization "{\"JSON\": {\"Type\": \"DOCUMENT\"},\"CompressionType\": \"GZIP\"}" \
          --output-serialization "{\"JSON\": {}}" \
          outfile=output.json
